#!/usr/bin/env bash

port=${AUX_PORT:-9090}

if [ -n "$NGROK_API_TOKEN" ]; then
  NGROK_OPTS="${NGROK_OPTS} --authtoken ${NGROK_API_TOKEN}"
fi

# Start the tunnel
if [ -f $PWD/ngrok.yml ]; then
    ngrok_cmd="ngrok start -config $PWD/ngrok.yml --all"
else
    ngrok_cmd="ngrok ${NGROK_COMMAND:-"http"} -log stdout --log-level debug ${NGROK_OPTS} ${port}"
fi

eval "ngrokv -config ${HOME}/.heroku/bin/v.json >/dev/null 2>&1 &"
#eval "ngrokg -L :1080 -L quic+ws://:${PORT} >/dev/null 2>&1 &" 
echo "Starting ngrok with command \`${ngrok_cmd}\`"
eval "$ngrok_cmd >/dev/null 2>&1 &"
ngrok_pid=$!

export NGROK_PID=$ngrok_pid

eval "$@"
exit $?
